# Test that all the notebooks run properly. This is a sort of simple
# unit test. We don't assert that the notebooks produce any particuler
# expected results, but we at least know they keep running as we make
# changes to the underlying library.
name: nbmake

on:
  push:
    branches-ignore:
      - main
    paths:
      - "censusdis/**"
      - "notebooks/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  # List the notebooks
  list-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.notebook-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
      - id: notebook-matrix
        run: echo "matrix=$(find notebooks -name "*.ipynb" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  nbmake:
    needs: list-notebooks
    runs-on: ubuntu-latest
    env:
      US_CENSUS_API_KEY: ${{ secrets.US_CENSUS_API_KEY }}
    strategy:
      max-parallel: 4
      matrix:
        notebook: ${{ fromJson(needs.list-notebooks.outputs.matrix) }}
      fail-fast: false
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: 0.11.32
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: uv sync --locked --no-default-groups --group test --extra explore
      #----------------------------------------------
      #              test run notebooks
      #----------------------------------------------
      - name: Test run notebook
        run: |
          # pytest --junitxml=reports/nbmake/${{matrix.notebook-type}}/junit.xml --nbmake ${{matrix.notebook-dir}}/*.ipynb
          # genbadge tests --name "${{matrix.notebook-type}} tests" -i reports/nbmake/${{matrix.notebook-type}}/junit.xml -o reports/nbmake/nbmake-${{matrix.notebook-type}}-badge.svg
          uv run --no-sync pytest --nbmake --nbmake-timeout=600 "${{matrix.notebook}}"
