# Run a matrix of tests across supported Python versions on Linux.
# This is run on each pull request.
#
# See also:
#    unit-test.yml: run on a single platform every time a branch is pushed
#    coverage-report.yml: runs on merge to main to generate coverage reports

name: test-matrix

on: pull_request

jobs:
  test-matrix:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    env:
      US_CENSUS_API_KEY: ${{ secrets.US_CENSUS_API_KEY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install GDAL build dependencies
        if: matrix.python-version == '3.14'
        run: |
          sudo apt-get update
          sudo apt-get install --yes libgdal-dev
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: 0.11.32
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: uv sync --locked --no-default-groups --group test
      - name: Log version
        run: >-
          uv run --no-sync python -c "import censusdis; print(f'censusdis version: {censusdis.version}')"
      - name: Run tests
        run: uv run --no-sync python -m pytest tests
      - name: Archive test artifacts
        if: ${{ !cancelled() && hashFiles('tests/_test_artifacts') != '' }}
        uses: actions/upload-artifact@v7
        with:
          name: test_artifacts-${{ matrix.python-version }}
          path: tests/_test_artifacts
          retention-days: 7
